# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   -I../../lib/message/cslib/src 
PKG_PATH =  -L../../lib/message/cslib/src 
PKG_LIB =   -lmessage 
PKG_CPP_DEPENDS = 
PKG_LINK_DEPENDS = 

PKG_SYSINC =  $(message_SYSINC) 
PKG_SYSLIB =  $(message_SYSLIB) 
PKG_SYSPATH = $(message_SYSPATH) 
